environment:

  matrix:

    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python27-x64"

    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python34-x64"

    # TODO
    #- PYTHON: "C:\\Python36"
    #- PYTHON: "C:\\Python36-x64"


install:

  # Upgrade to the latest version of pip to avoid it displaying warnings
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools"

  # do some manual dep installs that fix windows issues...
  - "%PYTHON%\\python.exe -m pip install pycparser"
  - "%PYTHON%\\python.exe -m pip install cryptography"

  # use setuptools to install deps
  - "%CMD_IN_ENV% %PYTHON%\\python.exe setup.py develop"

# no msbuild phase in the project
build: off

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% %PYTHON%\\python.exe -m unittest discover -v --fail"
